### ISSUE TITLE
Do we really need baloise specific CI?

### ISSUE THREAD

**Issue by christiansiegel** [baloise-incubator/gitopscli#18]
Why do we need baloise specific `ci.groovy` and `Dockerfile.baloise`?

**Comment by joachimprinzbach** [comment]
no, not anymore i think. We can just use the image from dockerhub with the base image approach you built. @niiku  Or do you see another case where we would still need it?

**Comment by joachimprinzbach** [comment]
Removed by @niiku, will close this
