### ISSUE TITLE
Allow updating of yaml lists

### ISSUE THREAD

**Issue by joachimprinzbach** [baloise-incubator/gitopscli#21]
- should we support adding an entry? And therefore also deleting?
- or just replacing the whole list with a new one?

**Comment by joachimprinzbach** [comment]
@niiku what do you think?

**Comment by joachimprinzbach** [comment]
I would also close this one - there is nothing to do imo

**Comment by christiansiegel** [comment]
+1
* Updating lists (inserting, adding, deleting, etc.) is not that trivial + I don't see a use case where this would be really necessary during deployment. 
* Replacing the whole list should already be possible
