### ISSUE TITLE
Redefining desired state shall not generate an error

### ISSUE THREAD

**Issue by patrit** [baloise-incubator/gitopscli#32]
Calling the cli with the same version again - i.e. no commit required - generates an error. According to kubernetes philosophy the desired state can be redefined without error.
Requested behaviour: Do not generate an error if no change is being generated.

**Comment by joachimprinzbach** [comment]
Can you provide more details? Which command did you execute?

**Comment by christiansiegel** [comment]
`deploy` - if you deploy the same again, the PR cannot be merged (no changes). I'm looking into it atm ;-)
