### ISSUE TITLE
Add PR Comment enhancements

### ISSUE THREAD

**Issue by joachimprinzbach** [baloise-incubator/gitopscli#37]
- remove unneeded params (branch, create-pr, auto-merge) #42 
- provide error handling and usefull log messages and return code when params are not correct 
- username / password invalid #49 
- org / repo combination not available #49 
- git_provider / git_provider_url not valid #49 
- pr with pr_id not available
  - Current message: ERROR:atlassian.rest_client:Received: 404
 Not Found
Pull request 2 does not exist in APPS/docker-sample-nginx.
- comment with id parent_id not available
  - Current message: ERROR:atlassian.rest_client:Received: 404
 Not Found
Comment 200 does not exist.
- any error while calling git server api
  - see current messages above

**Comment by joachimprinzbach** [comment]
@niiku @christiansiegel Added the current behaviour - what do you guys think? I would prefer to wrap things in a GitOpsException, instead of leaking gitserver specific exceptions and messages

**Comment by niiku** [comment]
Maybe only log the stacktrace when log level is debug - so no information gets swallowed

**Comment by christiansiegel** [comment]
We could add a `--verbose` flag, which sets the log level to debug instead of info

**Comment by christiansiegel** [comment]
added `--verbose` flag in #50 to log the full stack trace instead of an error one-liner
