### ISSUE TITLE
Create preview enhancements

### ISSUE THREAD

**Issue by joachimprinzbach** [baloise-incubator/gitopscli#40]
- provide error handling and usefull log messages and return code when params are not correct
- branch not available in apps repo #72 
- org / repo combination not available #49 
- .gitops.config.yaml not available in apps repo #75
- .gitops.config.yaml not readable, property missing #75
- root org / root repo org from .gitops.config.yaml not available #49 
- git_provider / git_provider_url not valid #49 
- pr with pr_id not available #72 
- ~comment with id parent_id not available~
- any error while calling git server api #49, #66
- preview-template for app not available #75
- no route host available #75
- property to replace not available in values.yaml #48
- any error while performing git operations #66, #67
- replace logic should work for non helm based projects -> separate issue for this feature #74

**Comment by christiansiegel** [comment]
While writing the documentation I noticed another issue:

the `--branch` parameter is currently used to locate the app repo branch as well as to create the PR branch in the deployment repo. This can potentially lead to branch collisions in the deployment repo. Plus, this is a kinda weird behavior.

Possible solution:
Detect the app repo branch based on the PR id. Use the `--branch` param to create the PR in the deployment repo (or push directly to master if wanted).

**Comment by joachimprinzbach** [comment]
@christiansiegel Yeah, I already noticed that as well - it is indeed not easy to follow for developers. One could also simply use a random branch name. Should we list alternatives?
Detecting the app repo branch sounds like a good idea, it is currently something that (in case of github) the ci has to do, as github does not provide this information in the pull request event payload. However, bitbucket does, so in case of bitbucket there is no need to retrieve branch absed on the prid.

**Comment by christiansiegel** [comment]
IMO all branches in the config repo can be random. That means, we can drop the `--branch` parameter for all commands. Default will be "master". And if `--create-pr` is given, a random branch will be created. Less to think about for the user.

Regarding github: you can find the branch name under `head.ref`: https://api.github.com/repos/baloise-incubator/gitopscli/pulls/71

**Comment by joachimprinzbach** [comment]
Well, this ist the REST API - but not the webhook payload. See https://developer.github.com/v3/activity/events/types/#pullrequestevent 

But it actually looks like as the payload got extended. Maybe the ref is now available. I will have a closer look later on today.

**Comment by joachimprinzbach** [comment]
Now I remember what the issue was: 

When commenting on a PR with e.g. /preview the GitHub Webhook payload does not contain the branch information: https://developer.github.com/v3/activity/events/types/#issuecommentevent

But nevertheless, one reason for the branch name was, that we have to checkout the apps repo (to obtain the gitops.config.yaml). We could get it from master, but then its not possible to test changes for that config file on a branch.

**Comment by christiansiegel** [comment]
I propose to drop the branch arg: #72 
- It's initial purpose was to specify the branch in the config repo. For `deploy`, we always provide a random name anyways. -> The CLI can generate the random branch name automatically
- For `create-preview` we always have the `--pr_id`. The CLI can fetch the app repo PR branch name from the API. The config repo branch can be randomly generated
- For `delete-preview` we still have to provide the app repo PR branch name via `--branch`. But the config repo branch can be randomly generated
