### ISSUE TITLE
Improve CLI commands' docs

### ISSUE THREAD

**Issue by christiansiegel** [baloise-incubator/gitopscli#61]
Add some prose documentation for every CLI command. Also, describe e.g. the required repo setup for some commands.

**Comment by christiansiegel** [comment]
`deploy` and `add-pr-comment` docs updated

**Comment by christiansiegel** [comment]
`sync-apps` doc updated

**Comment by joachimprinzbach** [comment]
@christiansiegel what is missing here?

**Comment by christiansiegel** [comment]
create and delete preview commands:
https://baloise-incubator.github.io/gitopscli/commands/create-preview/
https://baloise-incubator.github.io/gitopscli/commands/delete-preview/
